#!/bin/bash

token_header=()

if [ -n "$GITHUB_TOKEN" ]; then
  token_header=(-H "Authorization: token $GITHUB_TOKEN")
fi

if ( [ -n "$GH_APP" ] && [ -n "$GH_USER" ] ) || \
  ( [ -n "$GH_USER" ] && [ -n "$JWT_TOKEN" ] ) || \
  ( [ -n "$GH_APP" ] && [ -n "$JWT_TOKEN" ] ); then
  echo "Only one of user, app, or jwt can be set!" 1>&2
  exit 1
fi

if [ -n "$JWT_TOKEN" ]; then
  slug="$(curl -s -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $JWT_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/app" \
  | jq -r '.slug' )"

  if [ "$slug" == "null" ]; then
    echo "Unable to find app!" 1>&2
    exit 1
  fi
  GH_USER="$slug[bot]"
elif [ -n "$GH_APP" ]; then
  slug="$(printf '%s' "$GH_APP" | sed -E 's/[^a-zA-Z0-9]+/-/g;' | tr '[:upper:]' '[:lower:]' )"
  GH_USER="$slug[bot]"
elif [ -z "$GH_USER" ]; then
  echo "app, user, or jwp must be specified!" 1>&2
  exit 1
fi

user_enc="$(printf %s "$GH_USER" | jq -sRr @uri)"

user_data="$(curl -s -L \
  -H "Accept: application/vnd.github+json" \
  "${token_header[@]}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/users/$user_enc")"

user_id="$(echo "$user_data" | jq -r '.id' )"

if [ "$user_id" == "null" ]; then
  echo "Unable to find user!" 1>&2
  exit 1
fi

user_name="$(echo "$user_data" | jq -r '.name' )"
if [ "$user_name" == "null" ]; then
  user_name="$GH_USER"
fi

user_email="$(echo "$user_data" | jq -r '.email' )"
if [ "$NOREPLY" == 'true' ] || [ "$user_email" == "null" ]; then
  user_email="$user_id+$GH_USER@users.noreply.github.com"
fi

echo "user-login=$GH_USER"    >> "$GITHUB_OUTPUT"
echo "user-name=$user_name"   >> "$GITHUB_OUTPUT"
echo "user-id=$user_id"       >> "$GITHUB_OUTPUT"
echo "user-email=$user_email" >> "$GITHUB_OUTPUT"
